spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://106.52.253.199:1599;Databasename=Eqlee_User
    username: eqlee_dev
    password: dev2019@eqlee.com
